/* eslint-disable max-len */
/* eslint-disable react/jsx-filename-extension */
import React from 'react';
import { graphql } from 'gatsby';
import Layout from '../../components/Layout';
import Header from '../../components/reports/Header';
import About from '../../components/reports/About';
import NoImageSection from '../../components/reports/NoImageSection';

const Report0 = ({ data }) => {
  const sections = data.allMarkdownRemark.nodes;
  console.log(sections);
  return (
    <Layout title="Report 0: The MAPC Zoning Atlas - MAPC Zoning Atlas">
      <main className="main__wrapper main__wrapper--report">
        <Header />
        <About content={sections[0]} />
        <h3 id="introduction">Introduction</h3>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Unum facilisi duo et. Qui gloriatur scribentur et, id velit verear mel, cum no porro debet. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Scripta periculis ei eam, te pro movet reformidans. Scripta periculis ei eam, te pro movet reformidans. Usu ut commune mentitum, putent facete vim id. Dolor labitur cu pro. Vivendum intellegat et qui, ei denique consequuntur vix. Quot populo ad qui. Vivendum intellegat et qui, ei denique consequuntur vix. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Id mundi quando mandamus sit, est vide option accusata et. Id doctus accommodare eam, pri an esse tota prodesset, te veniam oblique posidonium mel. Semper aeterno percipit ut his, sea ex utinam referrentur repudiandae.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Unum facilisi duo et. Qui gloriatur scribentur et, id velit verear mel, cum no porro debet. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Scripta periculis ei eam, te pro movet reformidans. Scripta periculis ei eam, te pro movet reformidans. Usu ut commune mentitum, putent facete vim id. Dolor labitur cu pro. Vivendum intellegat et qui, ei denique consequuntur vix. Quot populo ad qui. Vivendum intellegat et qui, ei denique consequuntur vix. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Id mundi quando mandamus sit, est vide option accusata et. Id doctus accommodare eam, pri an esse tota prodesset, te veniam oblique posidonium mel. Semper aeterno percipit ut his, sea ex utinam referrentur repudiandae.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Unum facilisi duo et. Qui gloriatur scribentur et, id velit verear mel, cum no porro debet. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Scripta periculis ei eam, te pro movet reformidans. Scripta periculis ei eam, te pro movet reformidans. Usu ut commune mentitum, putent facete vim id. Dolor labitur cu pro. Vivendum intellegat et qui, ei denique consequuntur vix. Quot populo ad qui. Vivendum intellegat et qui, ei denique consequuntur vix. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Id mundi quando mandamus sit, est vide option accusata et. Id doctus accommodare eam, pri an esse tota prodesset, te veniam oblique posidonium mel. Semper aeterno percipit ut his, sea ex utinam referrentur repudiandae.
        </p>
        <h3 id="middle">Middle</h3>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Unum facilisi duo et. Qui gloriatur scribentur et, id velit verear mel, cum no porro debet. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Scripta periculis ei eam, te pro movet reformidans. Scripta periculis ei eam, te pro movet reformidans. Usu ut commune mentitum, putent facete vim id. Dolor labitur cu pro. Vivendum intellegat et qui, ei denique consequuntur vix. Quot populo ad qui. Vivendum intellegat et qui, ei denique consequuntur vix. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Id mundi quando mandamus sit, est vide option accusata et. Id doctus accommodare eam, pri an esse tota prodesset, te veniam oblique posidonium mel. Semper aeterno percipit ut his, sea ex utinam referrentur repudiandae.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Unum facilisi duo et. Qui gloriatur scribentur et, id velit verear mel, cum no porro debet. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Scripta periculis ei eam, te pro movet reformidans. Scripta periculis ei eam, te pro movet reformidans. Usu ut commune mentitum, putent facete vim id. Dolor labitur cu pro. Vivendum intellegat et qui, ei denique consequuntur vix. Quot populo ad qui. Vivendum intellegat et qui, ei denique consequuntur vix. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Id mundi quando mandamus sit, est vide option accusata et. Id doctus accommodare eam, pri an esse tota prodesset, te veniam oblique posidonium mel. Semper aeterno percipit ut his, sea ex utinam referrentur repudiandae.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Unum facilisi duo et. Qui gloriatur scribentur et, id velit verear mel, cum no porro debet. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Scripta periculis ei eam, te pro movet reformidans. Scripta periculis ei eam, te pro movet reformidans. Usu ut commune mentitum, putent facete vim id. Dolor labitur cu pro. Vivendum intellegat et qui, ei denique consequuntur vix. Quot populo ad qui. Vivendum intellegat et qui, ei denique consequuntur vix. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Id mundi quando mandamus sit, est vide option accusata et. Id doctus accommodare eam, pri an esse tota prodesset, te veniam oblique posidonium mel. Semper aeterno percipit ut his, sea ex utinam referrentur repudiandae.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Unum facilisi duo et. Qui gloriatur scribentur et, id velit verear mel, cum no porro debet. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Scripta periculis ei eam, te pro movet reformidans. Scripta periculis ei eam, te pro movet reformidans. Usu ut commune mentitum, putent facete vim id. Dolor labitur cu pro. Vivendum intellegat et qui, ei denique consequuntur vix. Quot populo ad qui. Vivendum intellegat et qui, ei denique consequuntur vix. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Id mundi quando mandamus sit, est vide option accusata et. Id doctus accommodare eam, pri an esse tota prodesset, te veniam oblique posidonium mel. Semper aeterno percipit ut his, sea ex utinam referrentur repudiandae.
        </p>
        <h3 id="conclusion">Conclusion</h3>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Unum facilisi duo et. Qui gloriatur scribentur et, id velit verear mel, cum no porro debet. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Scripta periculis ei eam, te pro movet reformidans. Scripta periculis ei eam, te pro movet reformidans. Usu ut commune mentitum, putent facete vim id. Dolor labitur cu pro. Vivendum intellegat et qui, ei denique consequuntur vix. Quot populo ad qui. Vivendum intellegat et qui, ei denique consequuntur vix. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Id mundi quando mandamus sit, est vide option accusata et. Id doctus accommodare eam, pri an esse tota prodesset, te veniam oblique posidonium mel. Semper aeterno percipit ut his, sea ex utinam referrentur repudiandae.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Unum facilisi duo et. Qui gloriatur scribentur et, id velit verear mel, cum no porro debet. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Scripta periculis ei eam, te pro movet reformidans. Scripta periculis ei eam, te pro movet reformidans. Usu ut commune mentitum, putent facete vim id. Dolor labitur cu pro. Vivendum intellegat et qui, ei denique consequuntur vix. Quot populo ad qui. Vivendum intellegat et qui, ei denique consequuntur vix. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Id mundi quando mandamus sit, est vide option accusata et. Id doctus accommodare eam, pri an esse tota prodesset, te veniam oblique posidonium mel. Semper aeterno percipit ut his, sea ex utinam referrentur repudiandae.
        </p>
        <h3 id="appendix">Appendix</h3>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Unum facilisi duo et. Qui gloriatur scribentur et, id velit verear mel, cum no porro debet. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Scripta periculis ei eam, te pro movet reformidans. Scripta periculis ei eam, te pro movet reformidans. Usu ut commune mentitum, putent facete vim id. Dolor labitur cu pro. Vivendum intellegat et qui, ei denique consequuntur vix. Quot populo ad qui. Vivendum intellegat et qui, ei denique consequuntur vix. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Id mundi quando mandamus sit, est vide option accusata et. Id doctus accommodare eam, pri an esse tota prodesset, te veniam oblique posidonium mel. Semper aeterno percipit ut his, sea ex utinam referrentur repudiandae.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Unum facilisi duo et. Qui gloriatur scribentur et, id velit verear mel, cum no porro debet. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Scripta periculis ei eam, te pro movet reformidans. Scripta periculis ei eam, te pro movet reformidans. Usu ut commune mentitum, putent facete vim id. Dolor labitur cu pro. Vivendum intellegat et qui, ei denique consequuntur vix. Quot populo ad qui. Vivendum intellegat et qui, ei denique consequuntur vix. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Id mundi quando mandamus sit, est vide option accusata et. Id doctus accommodare eam, pri an esse tota prodesset, te veniam oblique posidonium mel. Semper aeterno percipit ut his, sea ex utinam referrentur repudiandae.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Unum facilisi duo et. Qui gloriatur scribentur et, id velit verear mel, cum no porro debet. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Scripta periculis ei eam, te pro movet reformidans. Scripta periculis ei eam, te pro movet reformidans. Usu ut commune mentitum, putent facete vim id. Dolor labitur cu pro. Vivendum intellegat et qui, ei denique consequuntur vix. Quot populo ad qui. Vivendum intellegat et qui, ei denique consequuntur vix. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Id mundi quando mandamus sit, est vide option accusata et. Id doctus accommodare eam, pri an esse tota prodesset, te veniam oblique posidonium mel. Semper aeterno percipit ut his, sea ex utinam referrentur repudiandae.
        </p>
      </main>
    </Layout>
  );
};

export default Report0;
export const data = graphql`
query {
  allMarkdownRemark(filter: {frontmatter: {page: {in: "report0"}}}) {
    nodes {
      html
      id
      frontmatter {page, section, title, order}
    }
  }
}`;
